#!/usr/bin/env python3
"""Date Versioning - local dev server.

Builds the site (scripts/build.py), then serves _site/ at http://127.0.0.1:<port>. One route is
generated on the fly instead of read from disk: /assets/js/dev-mode.js, so DEV_MODE can be forced on
for local runs without ever touching the real, always-`false` file in assets/js/dev-mode.js.

Usage: python scripts/dev-server.py [port] [--no-dev-mode]
  port            default: 8080
  --no-dev-mode   don't force DEV_MODE on for this run (behave like production)

Copyright (c) 2026 Stux.Group. All rights reserved.
"""
import functools
import http.server
import socketserver
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = ROOT / "_site"


def main() -> None:
    port, dev_mode = 8080, True
    for arg in sys.argv[1:]:
        if arg == "--no-dev-mode":
            dev_mode = False
        elif arg.isdigit():
            port = int(arg)
        else:
            sys.exit(f"Unknown option: {arg}")

    subprocess.run([sys.executable, str(ROOT / "scripts" / "build.py")], check=True)

    class Handler(http.server.SimpleHTTPRequestHandler):
        extensions_map = {**http.server.SimpleHTTPRequestHandler.extensions_map,
                          ".md": "text/markdown; charset=utf-8", ".txt": "text/plain; charset=utf-8",
                          ".json": "application/json; charset=utf-8", ".svg": "image/svg+xml",
                          ".js": "text/javascript; charset=utf-8", ".css": "text/css; charset=utf-8"}

        def do_GET(self):  # noqa: N802
            if self.path.split("?")[0] == "/assets/js/dev-mode.js":
                body = f"// Generated by dev-server.py for this run.\nwindow.DEV_MODE = {'true' if dev_mode else 'false'};\n".encode()
                self.send_response(200)
                self.send_header("Content-Type", "text/javascript; charset=utf-8")
                self.send_header("Content-Length", str(len(body)))
                self.send_header("Cache-Control", "no-store")
                self.end_headers()
                self.wfile.write(body)
                return
            super().do_GET()

        def send_error(self, code, message=None, explain=None):
            if code == 404 and (SITE / "404.html").is_file():
                body = (SITE / "404.html").read_bytes()
                self.send_response(404)
                self.send_header("Content-Type", "text/html; charset=utf-8")
                self.send_header("Content-Length", str(len(body)))
                self.end_headers()
                if self.command != "HEAD":
                    self.wfile.write(body)
                return
            super().send_error(code, message, explain)

        def end_headers(self):
            self.send_header("Cache-Control", "no-cache")
            super().end_headers()

    handler = functools.partial(Handler, directory=str(SITE))
    socketserver.TCPServer.allow_reuse_address = True
    with socketserver.ThreadingTCPServer(("127.0.0.1", port), handler) as httpd:
        print(f"Date Versioning running at http://127.0.0.1:{port}")
        if dev_mode:
            print("DEV_MODE forced on for this run (banner shows). Pass --no-dev-mode to disable.")
        else:
            print("DEV_MODE forced off for this run: behaving like production.")
        print("Edits need a rebuild: stop the server and run it again.")
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print()


if __name__ == "__main__":
    main()
